routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\SportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'home'])->name('home');
Route::get('/dashboard', function(){ return view('dashboard'); })->name('dashboard');

Route::get('/events/my_events',  [EventController::class, 'my_events'])->name('events.my_events');
Route::get('/events/participate/{event}',  [EventController::class, 'participate'])->name('events.participate');

Route::resource( 'events', EventController::class );

Route::resource( 'sports', SportController::class );

// Route::get('sports/{sport:slug}', [SportController::class, 'show'])->name('sports.show');
require __DIR__.'/auth.php';

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\User;
use App\Models\Sport;

class Event extends Model
{
    use HasFactory;

    public $fillable = [
        'title',
        'description',
        'start_date',
        'user_id',
        'location'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function users()
    {
        return $this->belongsToMany(User::class, 'event_user');
    }

    public function sports()
    {
        return $this->belongsToMany(Sport::class, 'event_sport');
    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Models\Event;
use App\Models\User;
use App\Models\Sport;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $events = Event::with('user')->get();
        $users = User::with('events')->get();

        return view('events.index', [ 'events' => $events, 'users' => $users ]);
    }

    public function my_events()
    {
        $events = Event::with('user')->get();
        $users = User::with('events')->get();

        return view('events.my_events', [ 'events' => $events, 'users' => $users ]);
    }

    public function participate(Event $event)
    {
        $alreadyParticipate = in_array(   
            Auth::id(), 
            array_map(
                function($user) {
                    return $user["id"];
                }, 
                $event->users->toArray() ) );

        if( !$alreadyParticipate )
        {
            $event->users()->attach(Auth::id());
        }   

        return redirect('events');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $sports = Sport::all();

        return view('events.create', [ 'sports' => $sports ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $event = new Event();
        
        $event->fill( $request->all() );
        $event->save();
        $event->sports()->attach($request->sports);
        
        return redirect('events');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function show(Event $event)
    {
        return view('events.show', ['event' => $event]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function edit(Event $event)
    {
        return view('events.edit', ['event' => $event]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Event $event)
    {
        $request->validate([
            'title' => 'required|max:50'
            ]);
                    
        $event->fill( $request->all() );
        $event->save();

        return redirect('events');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function destroy( Event $event )
    {
        $sportIdArray = [];

        foreach( $event->sports as $sport )
        {
            $sportIdArray[] = $sport->id;
        }
        
        $event->sports()->detach( $sportIdArray );

        $event->delete();

        return redirect('events');
    }
}

resources/views/events/create.blade.php
<head>
    <meta charset="UTF-8">
    <title>Example</title>
    <script type="text/javascript"
            src="https://maps.googleapis.com/maps/api/js?key="></script>
    <script src="https://unpkg.com/location-picker/dist/location-picker.min.js"></script>
    <style type="text/css">
        #map {
        width: 100%;
        height: 480px;
        }
    </style>
</head>

<form method="POST" action="{{ route( 'events.store' ) }}">

    @csrf
    <input type="text" name="title"/> <br>
    <textarea name="description"></textarea>
    <select name="sports[]" multiple> 
            @foreach ($sports as $sport)
              <option value={{ $sport->id }}> {{ $sport->title }} </option>
            @endforeach
    </select>

    <input type="date" name="start_date"
        min='{{date("Y-m-d")}}'>

    <input type="hidden" id="location"  name="location" />
    <input type="hidden" name="user_id" value="{{Auth::id()}}" />

    <input type="submit" />

</form>


<div id="map"></div>

<script>

    var locationInput = document.getElementById('location');

  // Initialize locationPicker plugin
    var lp = new locationPicker('map', {
    setCurrentPosition: true, // You can omit this, defaults to true
    }, {
    zoom: 15 // You can set any google map options here, zoom defaults to 15
    });

  // Listen to map idle event, listening to idle event more accurate than listening to ondrag event
    google.maps.event.addListener(lp.map, 'idle', function (event) {
    // Get current location and show it in HTML
    var location = lp.getMarkerPosition();
    
    locationInput.value = '{"lat":'+location.lat+', "lon":'+location.lng+"}";
    });
</script>

resources/views/events/edit.blade.php
EDIT

@if (Auth::id() != $event->user_id )
    <script>window.location = "/";</script>
@endif

<form method="POST" action="{{ route( 'events.update', $event ) }}">
    @csrf
    @method('PUT')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <input type="text" name="title" value="{{ $event->title }}" /> <br>
    <textarea type="text" name="description"> {{ $event->description }} </textarea>

    <input type="submit" />

</form>

resources/views/events/index.blade.php
<h2>
    Events list    
</h2>

<ul>
    @foreach ($events as $event)
        <li> 
            <p><a href="{{ route( 'events.show', $event ) }}">{{ $event->title }}</a></p>
            <b>Owner:</b>
            <ul>
                <li> {{ $event->user->name }} </li>
            </ul>
            <b>Sports:</b>
            <ul>
                @foreach ($event->sports as $sport)
                    <li> {{ $sport->title }} </li>
                @endforeach
            </ul>
            <b>Users:</b>
            <ul>
                @foreach ($event->users as $user)
                    <li> {{ $user->name }} </li>
                @endforeach
            </ul>
            @php
                $alreadyParticipate = in_array(   Auth::id(), 
                            array_map(
                                function($user) {
                                    return $user["id"];
                                }, 
                                $event->users->toArray()) );
            @endphp
            @if( !$alreadyParticipate )
                <p><a href="{{ route( 'events.participate', $event ) }}">I'm in!</a></p>
            @endif
        </li>
    @endforeach
</ul>

resources/views/events/my_events.blade.php
<h2>
    My events    
</h2>

<ul>
    @foreach ($events as $event)
        @if (Auth::id() == $event->user_id)
            <li> 
                <p><a href="{{ route( 'events.show', $event ) }}">{{ $event->title }}</a></p>
                <b>Owner:</b>
                <ul>
                    <li> {{ $event->user->name }} </li>
                </ul>
                <b>Sports:</b>
                <ul>
                    @foreach ($event->sports as $sport)
                        <li> {{ $sport->title }} </li>
                    @endforeach
                </ul>
                <b>Users:</b>
                <ul>
                    @foreach ($event->users as $user)
                        <li> {{ $user->name }} </li>
                    @endforeach
                </ul>
            </li>
        @endif
    @endforeach
</ul>

resources/views/events/show.blade.php
<h1> {{ $event->title }} </h1>

(<a href="{{ route( 'events.edit', $event ) }}"> edit </a>)

<form method="POST" action="{{route('events.destroy', $event) }}">
@method('DELETE')
@csrf
    <button type="submit">Delete</button>
</form>